language: cpp

sudo: required

before_install:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq
  - sudo apt-get install -qq g++-6
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-6 90
  - sudo apt-get install uuid-dev
  - mkdir build
  - cd build
  - g++ --version

install:
  - cmake ..
  - make

cache:
  directories:
    - /usr